### ISSUE TITLE
Dataset source

### ISSUE THREAD

**Issue by sanglinwei** [locuslab/e2e-model-learning#12]
I wonder where the dataset of electricity price and load  is from ? I hope to use and refer the dataset in my work.

**Comment by priyald17** [comment]
The data is from the PJM electricity system operator. They have significantly improved their data portal since we wrote the paper, so I would definitely suggest pulling new and more recent data from their portal.

The PJM data portal is here: https://dataminer2.pjm.com/list

**Comment by priyald17** [comment]
The data is from the PJM electricity system operator. They have significantly improved their data portal since we wrote the paper, so I would definitely suggest pulling new and more recent data from their portal.

The PJM data portal is here: https://dataminer2.pjm.com/list

Notably, hourly load is [here](https://dataminer2.pjm.com/feed/hrl_load_metered/definition). They have various versions of locational marginal prices (LMPs) depending on what makes the most sense for your setting, e.g, [real-time five-minute LMPs](https://dataminer2.pjm.com/feed/rt_fivemin_hrl_lmps/definition) and [day-ahead hourly LMPs](https://dataminer2.pjm.com/feed/da_hrl_lmps/definition).

**Comment by sanglinwei** [comment]
Thank you for your kindness.
